{{- if and (not .Values.existingSecret) .Values.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent-vault.secretName" . }}
  labels:
    {{- include "agent-vault.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
