apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent-vault.fullname" . }}
  labels:
    {{- include "agent-vault.labels" . | nindent 4 }}
  {{- with .Values.service.api.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "agent-vault.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent-vault.fullname" . }}-proxy
  labels:
    {{- include "agent-vault.labels" . | nindent 4 }}
  {{- with .Values.service.proxy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.proxy.type }}
  ports:
    - port: {{ .Values.service.proxy.port }}
      targetPort: proxy
      protocol: TCP
      name: proxy
  selector:
    {{- include "agent-vault.selectorLabels" . | nindent 4 }}
